# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24e4ff6571369e5d037a665807ec0ecf7bd690f6d38130d05c11f68a27b3b19676a434e0fc95574670dd7817fc45c88c46e8acfb64ddcdaa2b27d92af59d52c9

test:
  secret_key_base: 060d9049b9d285b405d88bddc3a0b1c588750160e29f9d9bd30424897c69787e18d3fa53568fc8e28a94c2b43050a315afc4dc74c59acfb187826b316d646583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
