# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d0d479c447e89e34aee2ad3eaf58406652f9e9021821cfd1dff5d0f7cc4e44ae45a6da24938402b83dc65e995150ee2599a745eb4ca5277b6ce0fa239588b4d

test:
  secret_key_base: 54399e2d4db05b32ca6f12e1190a35e8e0cb53528228d6990c2e9fa6e9f0d1dc31b67b599d0845355a7d3808b7767f352afdfdd3fdd9c6d4a25464fa0ffdf32f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
